/// Service for word spelling suggestions
/// Uses Levenshtein distance for fuzzy matching against common English words
class SpellingSuggestionService {
  // Singleton pattern
  static final SpellingSuggestionService _instance =
      SpellingSuggestionService._internal();
  factory SpellingSuggestionService() => _instance;
  SpellingSuggestionService._internal();

  /// Get spelling suggestion for a potentially misspelled word
  /// Returns null if word appears correct or no close match found
  String? getSuggestion(String word) {
    if (word.isEmpty || word.length < 3) return null;

    final wordLower = word.toLowerCase().trim();

    // If the word exists in our list, it's correct
    if (_commonWords.contains(wordLower)) return null;

    // Find closest match using Levenshtein distance
    String? bestMatch;
    int bestDistance = 999;

    // Only consider words within reasonable edit distance
    // Max distance scales with word length (1-2 for short, 2-3 for medium, 3-4 for long)
    final maxDistance = (wordLower.length / 3).ceil().clamp(1, 4);

    for (final candidate in _commonWords) {
      // Skip if length difference is too large
      if ((candidate.length - wordLower.length).abs() > maxDistance) continue;

      final distance = _levenshteinDistance(wordLower, candidate);

      if (distance < bestDistance && distance <= maxDistance) {
        bestDistance = distance;
        bestMatch = candidate;
      }

      // Perfect phonetic match - stop early
      if (distance == 1) break;
    }

    // Only return if we found a reasonably close match
    // and it's not the same as input (case-insensitive)
    if (bestMatch != null && bestMatch.toLowerCase() != wordLower) {
      return bestMatch;
    }

    return null;
  }

  /// Calculate Levenshtein distance between two strings
  int _levenshteinDistance(String a, String b) {
    if (a.isEmpty) return b.length;
    if (b.isEmpty) return a.length;

    // Create a 2D matrix
    final matrix = List.generate(
      a.length + 1,
      (i) => List.generate(b.length + 1, (j) => 0),
    );

    // Initialize first row and column
    for (int i = 0; i <= a.length; i++) {
      matrix[i][0] = i;
    }
    for (int j = 0; j <= b.length; j++) {
      matrix[0][j] = j;
    }

    // Fill in the matrix
    for (int i = 1; i <= a.length; i++) {
      for (int j = 1; j <= b.length; j++) {
        final cost = a[i - 1] == b[j - 1] ? 0 : 1;
        matrix[i][j] = [
          matrix[i - 1][j] + 1, // deletion
          matrix[i][j - 1] + 1, // insertion
          matrix[i - 1][j - 1] + cost, // substitution
        ].reduce((a, b) => a < b ? a : b);
      }
    }

    return matrix[a.length][b.length];
  }

  /// Common English words likely to be looked up while reading literature
  /// Focused on challenging vocabulary that readers often misspell
  static const Set<String> _commonWords = {
    // A
    'abate',
    'aberration',
    'abhor',
    'abstain',
    'abstruse',
    'accolade',
    'acquiesce',
    'acrimony',
    'aesthetic',
    'affable',
    'aggregate',
    'alacrity',
    'allegory',
    'alleviate',
    'altruism',
    'amalgamate',
    'ambiguous',
    'ambivalent',
    'ameliorate',
    'anachronism',
    'analogous',
    'anathema',
    'anomaly',
    'antithesis',
    'apathy',
    'appease',
    'archaic',
    'arduous',
    'articulate',
    'ascetic',
    'aspersion',
    'assiduous',
    'augment',
    'auspicious',
    'austere',
    'autonomous',
    'avarice',

    // B
    'banal',
    'belligerent',
    'benevolent',
    'bequeath',
    'bombastic',
    'bourgeois',
    'brevity',
    'bucolic',
    'burgeon',

    // C
    'cacophony',
    'calamity',
    'candor',
    'capitulate',
    'capricious',
    'catalyst',
    'catharsis',
    'caustic',
    'censure',
    'cerebral',
    'chagrin',
    'charlatan',
    'circumlocution',
    'circumspect',
    'clandestine',
    'clemency',
    'coalesce',
    'cognizant',
    'colloquial',
    'commensurate',
    'compendium',
    'complacent',
    'complicity',
    'conciliatory',
    'condescend',
    'confluence',
    'congenial',
    'conjecture',
    'connoisseur',
    'conscientious',
    'consensus',
    'consonance',
    'conspicuous',
    'consternation',
    'contentious',
    'contiguous',
    'contrite',
    'conundrum',
    'conventional',
    'convivial',
    'copious',
    'corollary',
    'corroborate',
    'cosmopolitan',
    'countenance',
    'credulous',
    'culpable',
    'cursory',
    'cynical',

    // D
    'dauntless',
    'dearth',
    'debacle',
    'decorum',
    'deferential',
    'deleterious',
    'delineate',
    'demagogue',
    'demeanor',
    'denigrate',
    'denounce',
    'deride',
    'derivative',
    'despondent',
    'destitute',
    'desultory',
    'diatribe',
    'dichotomy',
    'didactic',
    'diffident',
    'dilapidated',
    'dilatory',
    'diligent',
    'discern',
    'discord',
    'discourse',
    'discrepancy',
    'discrete',
    'disdain',
    'disinterested',
    'disparage',
    'disparate',
    'dissemble',
    'disseminate',
    'dissonance',
    'divergent',
    'docile',
    'dogmatic',
    'dour',
    'dubious',
    'duplicity',

    // E
    'ebullient',
    'eccentric',
    'eclectic',
    'edifice',
    'effervescent',
    'efficacious',
    'effrontery',
    'egalitarian',
    'egregious',
    'elegy',
    'elocution',
    'eloquent',
    'elucidate',
    'elusive',
    'emanate',
    'emancipate',
    'embellish',
    'emollient',
    'empathy',
    'empirical',
    'emulate',
    'enervate',
    'engender',
    'enigmatic',
    'ennui',
    'ephemeral',
    'epiphany',
    'epitome',
    'equanimity',
    'equivocal',
    'eradicate',
    'erudite',
    'esoteric',
    'espouse',
    'ethereal',
    'euphemism',
    'evanescent',
    'exacerbate',
    'exasperate',
    'exculpate',
    'exemplary',
    'exigent',
    'existential',
    'exonerate',
    'expedient',
    'explicit',
    'exposition',
    'extemporaneous',
    'extol',
    'extraneous',
    'extricate',
    'exuberant',

    // F
    'facetious',
    'fallacious',
    'fastidious',
    'fatuous',
    'fecund',
    'felicitous',
    'fervent',
    'fervid',
    'fidelity',
    'figurative',
    'flagrant',
    'florid',
    'foment',
    'forbearance',
    'formidable',
    'fortuitous',
    'fractious',
    'frivolous',
    'frugal',
    'furtive',
    'futile',

    // G
    'garrulous',
    'germane',
    'gratuitous',
    'gregarious',
    'guileless',

    // H
    'hackneyed',
    'harangue',
    'harbinger',
    'hedonism',
    'hegemony',
    'heresy',
    'heterogeneous',
    'hierarchy',
    'histrionic',
    'homogeneous',
    'hubris',
    'hyperbole',
    'hypocritical',

    // I
    'iconoclast',
    'idiosyncratic',
    'ignominious',
    'illicit',
    'immutable',
    'impartial',
    'impeccable',
    'impecunious',
    'impede',
    'imperious',
    'impertinent',
    'impervious',
    'impetuous',
    'implausible',
    'implicit',
    'impudent',
    'impugn',
    'inadvertent',
    'incendiary',
    'inchoate',
    'incisive',
    'incongruous',
    'inconsequential',
    'incontrovertible',
    'incorrigible',
    'incredulous',
    'indifferent',
    'indigenous',
    'indigent',
    'indignant',
    'indolent',
    'indomitable',
    'indulgent',
    'ineffable',
    'ineluctable',
    'inept',
    'inexorable',
    'infallible',
    'ingenuous',
    'inherent',
    'inimical',
    'innocuous',
    'innuendo',
    'inscrutable',
    'insidious',
    'insipid',
    'insolent',
    'insouciant',
    'intangible',
    'integral',
    'intercede',
    'interminable',
    'intractable',
    'intransigent',
    'intrepid',
    'intrinsic',
    'introspective',
    'inundate',
    'inure',
    'invective',
    'inveterate',
    'invidious',
    'irascible',
    'irreverent',
    'itinerant',

    // J
    'jaundiced',
    'jettison',
    'judicious',
    'juxtapose',

    // K
    'kinetic',

    // L
    'laconic',
    'lament',
    'languish',
    'lassitude',
    'latent',
    'laudable',
    'lethargic',
    'levity',
    'licentious',
    'limpid',
    'lithe',
    'litigious',
    'loquacious',
    'lucid',
    'lugubrious',
    'luminous',

    // M
    'magnanimous',
    'malevolent',
    'malfeasance',
    'malign',
    'malleable',
    'maudlin',
    'maverick',
    'melancholy',
    'mendacious',
    'mercurial',
    'meritorious',
    'meticulous',
    'misanthrope',
    'mitigate',
    'modicum',
    'mollify',
    'moribund',
    'morose',
    'multifarious',
    'mundane',
    'munificent',
    'myopic',

    // N
    'nascent',
    'nebulous',
    'nefarious',
    'negligible',
    'neophyte',
    'nihilism',
    'nonchalant',
    'nonplussed',
    'nostalgia',
    'notorious',
    'nuance',

    // O
    'obdurate',
    'obfuscate',
    'oblique',
    'oblivious',
    'obscure',
    'obsequious',
    'obsolete',
    'obstinate',
    'obstreperous',
    'obtuse',
    'officious',
    'ominous',
    'onerous',
    'opaque',
    'opportunist',
    'opprobrium',
    'orthodox',
    'oscillate',
    'ostentatious',
    'ostracize',

    // P
    'palatable',
    'palliate',
    'palpable',
    'panacea',
    'paradigm',
    'paradox',
    'paragon',
    'parochial',
    'parsimonious',
    'partisan',
    'pathological',
    'patronize',
    'paucity',
    'pedantic',
    'pejorative',
    'pellucid',
    'penchant',
    'penitent',
    'pensive',
    'penurious',
    'perennial',
    'perfidious',
    'perfunctory',
    'peripheral',
    'pernicious',
    'perpetuate',
    'perquisite',
    'perspicacious',
    'pertinent',
    'pervasive',
    'petulant',
    'philistine',
    'phlegmatic',
    'piety',
    'pinnacle',
    'pithy',
    'placate',
    'placid',
    'platitude',
    'plausible',
    'plenitude',
    'poignant',
    'polemic',
    'ponderous',
    'portentous',
    'pragmatic',
    'precedent',
    'preclude',
    'precocious',
    'precursor',
    'predilection',
    'preeminent',
    'prescient',
    'presumptuous',
    'pretentious',
    'prevalent',
    'prevaricate',
    'pristine',
    'probity',
    'proclivity',
    'prodigal',
    'prodigious',
    'profligate',
    'profound',
    'profuse',
    'proliferate',
    'prolific',
    'prolix',
    'propensity',
    'propitious',
    'propriety',
    'prosaic',
    'proscribe',
    'protean',
    'provincial',
    'provoke',
    'prudent',
    'puerile',
    'pugnacious',
    'punctilious',
    'pungent',
    'pusillanimous',

    // Q
    'quagmire',
    'qualm',
    'quandary',
    'querulous',
    'quiescent',
    'quintessential',
    'quixotic',

    // R
    'rancor',
    'rapacious',
    'raucous',
    'rebuke',
    'recalcitrant',
    'recant',
    'recapitulate',
    'reciprocate',
    'reclusive',
    'reconcile',
    'recondite',
    'rectitude',
    'redolent',
    'redundant',
    'refractory',
    'refute',
    'reiterate',
    'relegate',
    'relinquish',
    'remonstrate',
    'renege',
    'replete',
    'reprehensible',
    'reprobate',
    'repudiate',
    'requisite',
    'rescind',
    'resigned',
    'resilient',
    'resolute',
    'resonate',
    'respite',
    'resplendent',
    'restitution',
    'restive',
    'resurgent',
    'reticent',
    'retribution',
    'reverent',
    'rhetoric',
    'ribald',
    'rigorous',
    'robust',
    'rudimentary',

    // S
    'sacrosanct',
    'sagacious',
    'salient',
    'salutary',
    'sanction',
    'sanguine',
    'sardonic',
    'satiate',
    'satire',
    'scintillate',
    'scrupulous',
    'scrutinize',
    'sedulous',
    'semblance',
    'sensuous',
    'sentient',
    'serendipity',
    'servile',
    'sinuous',
    'skeptical',
    'sobriety',
    'solicitous',
    'solipsistic',
    'somnolent',
    'sonorous',
    'sophistry',
    'soporific',
    'sordid',
    'specious',
    'sporadic',
    'spurious',
    'squalid',
    'squander',
    'stagnant',
    'steadfast',
    'stigmatize',
    'stipulate',
    'stoic',
    'stratagem',
    'strident',
    'stringent',
    'stymie',
    'subjugate',
    'sublime',
    'submissive',
    'subordinate',
    'subsequent',
    'subservient',
    'substantiate',
    'subtle',
    'subversive',
    'succinct',
    'succumb',
    'superficial',
    'superfluous',
    'supplant',
    'supplicate',
    'surfeit',
    'surmise',
    'surreptitious',
    'sycophant',
    'synthesis',

    // T
    'tacit',
    'taciturn',
    'tangential',
    'tantalize',
    'tantamount',
    'tedious',
    'temerity',
    'temperament',
    'tempestuous',
    'temporal',
    'tenable',
    'tenacious',
    'tendentious',
    'tenuous',
    'terse',
    'timorous',
    'tirade',
    'torpid',
    'tortuous',
    'tractable',
    'transient',
    'trepidation',
    'truculent',
    'truncate',
    'tumultuous',
    'turgid',
    'turpitude',
    'tyranny',

    // U
    'ubiquitous',
    'umbrage',
    'unctuous',
    'undermine',
    'unequivocal',
    'unfathomable',
    'unprecedented',
    'unscrupulous',
    'unwitting',
    'upbraid',
    'urbane',
    'usurp',
    'utilitarian',

    // V
    'vacillate',
    'vacuous',
    'vapid',
    'variegated',
    'vehement',
    'venerable',
    'venerate',
    'veracity',
    'verbose',
    'verdant',
    'verisimilitude',
    'vernacular',
    'vestige',
    'vicarious',
    'vicissitude',
    'vigilant',
    'vilify',
    'vindicate',
    'vindictive',
    'virtuoso',
    'virulent',
    'visceral',
    'vitriolic',
    'vituperative',
    'vivacious',
    'vociferous',
    'volatile',
    'volition',
    'voluminous',
    'voracious',

    // W
    'wanton',
    'wary',
    'whimsical',
    'wistful',
    'wrath',

    // Z
    'zealous',
    'zenith',
  };
}
